SingleSpaceBeforeFirstArg been renamed
Error: The `Style/SingleSpaceBeforeFirstArg` cop has been renamed to `Style/SpaceBeforeFirstArg. 
(obsolete configuration found in /home/travis/build/bloomberg/zookeeper-cookbook/.rubocop.yml, please update it)
RuboCop failed!